# Run task on CLI
# @name runCliFiles

@apiKey = {{$dotenv API_KEY}}

POST {{apiUrl}}/cli-files
Content-Type: application/json
X-API-Key: {{apiKey}}

{
  "source": "cli",
  "args": {
    "batch_id": "{{$guid}}",
    "files": [
      {
        "name": "src/app.module.ts",
        "content_type": "text/plain"
      },
      {
        "name": "src/entrypoint.ts",
        "content_type": "text/plain"
      }
    ]
  }
}